name: Run build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
    - name: Setup Gradle
      uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
    - name: Build with Gradle
      run: ./gradlew foo
      env:
        GRADLE_BUILD_ACTION_CACHE_DEBUG_ENABLED: true
        CONFIG_SECRET: Secret for config
        TASK_SECRET: Secret for task
        CACHE_SECRET: Secret for cache
        REPO_SECRET: Secret for repo
